name: Build and Deploy Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: app

      - name: Run tests
        run: npm test
        working-directory: app

  build:
    name: Build Lambda
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: app

      - name: Build the project
        run: npm run build
        working-directory: app

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-dist
          path: app/dist

  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    needs: build

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-dist
          path: app/dist

      - name: Check dist folder
        run: ls -la app/dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config=dev.aws.tfbackend
        working-directory: infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=dev.tfvars
        working-directory: infra